### ISSUE TITLE
 (NamiEntitlementManager.isEntitlementActive("premium_access")) {
    // allow access to premium app features 
}

### ISSUE THREAD

**Issue by FAIZFREADY** [namiml/nami-android#14]
"com.namiml:sdk-android:1.1.1" 
}android {
  ...
  // Configure only for each module that uses Java 8
  // language features (either in its source code or
  // through dependencies).
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }
  // For Kotlin projects
  kotlinOptions {
    jvmTarget = JavaVersion.VERSION_1_8.toString()
  }
}"com.namiml:sdk-android:1.1.1" 
}import com.namiml.Nami
import com.namiml.NamiConfiguration
import com.namiml.NamiLogLevel
  
class DemoApplication : Application() {
  
  companion object {
    private const val NAMI_APP_PLATFORM_ID = "YOUR_APP_PLATFORM_ID"
  }
    
  override fun onCreate() {
    super.onCreate()
    Nami.configure(
      NamiConfiguration.build(this, NAMI_APP_PLATFORM_ID) {
        LogLevel = NamiLogLevel.INFO.takeIf { BuildConfig.DEBUG } ?: NamiLogLevel.WARN
      }
    )
  }
}import com.namiml.paywall.NamiPaywallManager
import android.util.Log
  
const val LOG_TAG = "ExampleApp"
  
class ExampleActivity : AppCompatActivity() {
  
  private fun onPaywallRaise(Activity activity) {
    NamiPaywallManager.preparePaywallForDisplay { success, error ->
      if (success) {
        NamiPaywallManager.raisePaywall(activity)
      } else {
        Log.w(LOG_TAG, "preparePaywallForDisplay failed -> $error")
      }
    }
  }
}

**Comment by acantarero** [comment]
I don't see any question in here so closing this issue.  Feel free to reach out to support@namiml.com if you have a question about integrating the Android SDK with your app.
