### ISSUE TITLE
issue with compileOptions for JavaVersion.VERSION_21 in latest nami sdk

### ISSUE THREAD

**Issue by vishalmakwana8** [namiml/nami-android#78]
Hi, 
I am using latest android studio ladybug version. For this I am using latest Gradle 8.9 and Java version 21. After updating latest version 3.2.7. 

I am facing below error. Can you provide the any resolution to fix this issue?
same issue facing for 3.2.6.

<img width="678" alt="Screenshot 2024-11-03 at 2 54 44 PM" src="https://github.com/user-attachments/assets/22723ce5-853d-4460-9b10-9500ba6f07ca">

**Comment by namidan** [comment]
HI @vishalmakwana8  

It looks like you need to add the core de-sugaring library per this doc:
https://learn.namiml.com/public-docs/integrations/billing-platforms/google-integration/troubleshooting/supporting-android-minsdkversion-25-or-lower

**Comment by vishalmakwana8** [comment]
Hi @namidan, 
Thank you for your response. This solution is working fine for me.
